Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -18,6 +18,9 @@ jobs:
       with:
         go-version: '1.20'
 
+    - name: Check if config.txt exists
+      run: test -f config.txt || echo "::error::config.txt not found"
+
     - name: Copy config.txt
       run: cp config.txt .
 
